name: Check SOLD OUT

on:
  schedule:
    - cron: "30 11 * * *" # JST 20:30
  workflow_dispatch:

jobs:
  check-soldout:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Reset if previous commit is by action@github.com
        run: |
          PREV_EMAIL=$(git log -1 --pretty=format:'%ae' | tail -n 1)
          if [ "$PREV_EMAIL" = "action@github.com" ]; then
            echo "[Actions] Previous commit by action@github.com, running git reset --hard HEAD~1"
            git reset --hard HEAD~1
          else
            echo "[Actions] Previous commit not by action@github.com, skipping reset"
          fi

      - name: Read result file
        id: read_result_1st
        run: echo "result=$(cat docs/result.txt)" >> $GITHUB_OUTPUT

      - name: Check skip conditions
        id: skip
        run: |
          day=$(TZ=Asia/Tokyo date +%u)
          FLAG_SKIP=false
          if [ "$day" -ge 6 ] || \
             [ "${{ steps.read_result_1st.outputs.result }}" != "0" ]; then
            FLAG_SKIP=true
            echo "[check_2nd.yml] Skipping workflow."
          fi
          echo "flag_skip=$FLAG_SKIP" >> $GITHUB_OUTPUT

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: "true"
      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run Python scripts
        id: run_scripts
        if: steps.skip.outputs.flag_skip != 'true'
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          uv run script/get_posts.py
          uv run script/filter_posts.py
          uv run script/check_status.py
          uv run script/update_pages.py

      - name: Commit new Pages status
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          branch: main
          push_options: "--force"
          commit_message: "あじよしの営業状況：${{ steps.run_scripts.outputs.status }}"
          commit_user_name: "gh-actions[bot]"
          commit_user_email: "action@github.com"
          commit_author: "gh-actions[bot] <action@github.com>"
