name: Check SOLD OUT

on:
  schedule:
    - cron: "30 11 * * *" # JST 20:30
  workflow_dispatch:

jobs:
  check-soldout:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # mainブランチをチェックアウト
      - name: Checkout main branch
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      # docs/result.txtを読み込む
      - name: Read result file
        id: read_result_1st
        run: echo "result=$(cat docs/result.txt)" >> $GITHUB_OUTPUT

      # 土日またはOPENでない場合にはスキップ
      - name: Check skip conditions
        id: skip
        run: |
          day=$(TZ=Asia/Tokyo date +%u)
          FLAG_SKIP=false
          if [ "$day" -ge 6 ] || \
             [ "${{ steps.read_result_1st.outputs.result }}" != "0" ]; then
            FLAG_SKIP=true
            echo "[check_2nd.yml] Skipping workflow."
          fi
          echo "flag_skip=$FLAG_SKIP" >> $GITHUB_OUTPUT

      # uvでPython環境をセットアップ
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          working-directory: script
          activate-environment: "true"
      - name: Install the project
        run: uv sync --locked --all-extras --dev --project script

      # Pythonスクリプト実行（get → filter → check）
      - name: Run Python scripts
        if: steps.skip.outputs.flag_skip != 'true'
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          uv run script/get_posts.py
          uv run script/filter_posts.py
          uv run script/check_status.py
          uv run script/update_pages.py

      # コミット＆プッシュ
      - name: Commit new Pages status
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          branch: main
          commit_message: "あじよしの営業状況：${{ steps.update_pages.outputs.status }}"
          commit_user_name: "gh-actions[bot]"
          commit_user_email: "action@github.com"
          commit_author: "gh-actions[bot] <action@github.com>"
