name: Check SOLD OUT

on:
  schedule:
    - cron: "30 11 * * *" # JST 20:30
  workflow_dispatch:

jobs:
  check-soldout:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # まずgh-actionsブランチを取得
      - name: Checkout gh-actions branch
        uses: actions/checkout@v5
        with:
          ref: gh-actions
          fetch-depth: 0

      # テキストファイルを一時ディレクトリにコピー
      - name: Backup text files
        run: |
          mkdir -p /tmp/txt
          cp result.txt /tmp/txt/result.txt
          cp status.txt /tmp/txt/status.txt

      # mainブランチをチェックアウト
      - name: Checkout main branch
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0

      # 一時保存していたテキストファイルを戻す
      - name: Restore text files
        run: |
          cp /tmp/txt/result.txt result.txt
          cp /tmp/txt/status.txt status.txt

      # result.txtを読み込む
      - name: Read result file
        id: read_result_1st
        run: echo "result=$(cat result.txt)" >> $GITHUB_OUTPUT

      # 土日またはOPENでない場合にはスキップ
      - name: Check skip conditions
        id: skip
        run: |
          day=$(TZ=Asia/Tokyo date +%u)
          FLAG_SKIP=false
          if [ "$day" -ge 6 ] || \
             [ "${{ steps.read_result_1st.outputs.result }}" = "0" ]; then
            FLAG_SKIP=true
            echo "[Actions] Skipping workflow."
          fi
          echo "flag_skip=$FLAG_SKIP" >> $GITHUB_OUTPUT

      # uvでPython環境をセットアップ
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          working-directory: script
          activate-environment: "true"
      - name: Install the project
        run: uv sync --locked --all-extras --dev --project script

      # Pythonスクリプト実行（get → filter → check）
      - name: Run Python scripts
        if: steps.skip.outputs.flag_skip != 'true'
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          uv run script/get_posts.py
          uv run script/filter_posts.py
          uv run script/check_status.py

      # 新しいテキストファイルを再度/tmpにコピー
      - name: Save updated text files
        run: |
          cp result.txt /tmp/txt/result.txt
          cp status.txt /tmp/txt/status.txt

      # gh-actionsブランチに戻る
      - name: Checkout gh-actions branch again
        uses: actions/checkout@v5
        with:
          ref: gh-actions
          fetch-depth: 0

      # テキストファイルを戻す
      - name: Restore final text files
        run: |
          cp /tmp/txt/result.txt result.txt
          cp /tmp/txt/status.txt status.txt

      # docs/index.mdの更新
      - name: Update Pages
        id: update_pages
        run: |
          RESULT=$(cat result.txt)
          STATUS=$(cat status.txt)

          DATE=$(TZ='Asia/Tokyo' date '+%Y-%m-%d %H:%M %Z')
          echo "[Actions] STATUS=$STATUS DATE=$DATE"

          sed -z -i "s|<!--RESULT_START-->.*<!--RESULT_END-->|<!--RESULT_START-->$STATUS<!--RESULT_END-->|" docs/index.md
          sed -z -i "s|<!--DATE_START-->.*<!--DATE_END-->|<!--DATE_START-->$DATE<!--DATE_END-->|" docs/index.md

          echo "status=$STATUS" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT

      # コミット＆プッシュ
      - name: Commit new Pages status
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          branch: gh-actions
          commit_message: "auto: あじよしは現在 ${{ steps.update_pages.outputs.status }}"
          commit_user_name: "gh-actions[bot]"
          commit_user_email: "action@github.com"
          commit_author: "gh-actions[bot] <action@github.com>"
