name: Format

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
      - "**/*.csv"
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: astral-sh/ruff-action@v3
        with:
          version: ">=0.14.0"
          args: "format"
          src: "./script"
      - uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          branch: main
          commit_message: "style: Format code with Ruff"
          commit_user_name: "gh-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "gh-actions[bot] <github-actions[bot]@users.noreply.github.com>"

  clang-format:
    needs: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - run: |
          sudo apt install clang-format -y
          find ESP-WROOM-02/src \( -name '*.hpp' -o -name '*.cpp' \) \
          | xargs -r clang-format -i -style=file:ESP-WROOM-02/src/.clang-format
      - uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          branch: main
          commit_message: "style[ESP-WROOM-02]: Format code with clang-format"
          commit_user_name: "gh-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "gh-actions[bot] <github-actions[bot]@users.noreply.github.com>"
