name: Format code

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  prettier-format:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Enable Yarn
        run: |
          npm uninstall -g yarn
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn install --immutable
      - name: Run Prettier
        run: |
          yarn format
      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          branch: main
          commit_message: 'style: Format code with Prettier'
          commit_user_name: 'gh-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'gh-actions[bot] <github-actions[bot]@users.noreply.github.com>'

  ruff-format:
    needs: prettier-format
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Run Ruff Formatter
        uses: astral-sh/ruff-action@v3
        with:
          version: '>=0.14.0'
          args: 'format'
          src: './script'
      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          branch: main
          commit_message: 'style: Format code with Ruff'
          commit_user_name: 'gh-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'gh-actions[bot] <github-actions[bot]@users.noreply.github.com>'

  clang-format:
    needs: ruff-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Run clang-format
        run: |
          sudo apt install clang-format -y
          clang-format -i -style=file:".clang-format" */src/**/*.h  
          clang-format -i -style=file:".clang-format" */src/**/*.c
      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          branch: main
          commit_message: 'style: Format code with clang-format'
          commit_user_name: 'gh-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'gh-actions[bot] <github-actions[bot]@users.noreply.github.com>'
