name: Ruff Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - 'script/**'
      - '.github/workflows/ruff-lint.yml'

jobs:
  ruff-lint:
    name: Required processes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out
        uses: actions/checkout@v5
      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v3
        with:
          version: '>=0.14.0'
          args: 'check'
          src: './script'
