name: Ruff Format

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "script/**"
      - ".github/workflows/ruff-format.yml"

jobs:
  ruff-format:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Run Ruff Formatter
        uses: astral-sh/ruff-action@v3
        with:
          version: ">=0.14.0"
          args: "format"
          src: "./script"
      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          branch: main
          commit_message: "style: Format code with Ruff"
          commit_user_name: "gh-actions[bot]"
          commit_user_email: "action@github.com"
          commit_author: "gh-actions[bot] <action@github.com>"
